### PR TITLE
Fix issue #876 - column reference "_age_default_alias_0" is ambiguous

### LINKED ISSUE #876: Unexpected Error: column reference "_age_default_alias_0" is ambiguous
When running the following query:
```cypher
MATCH ({n0:0}) MATCH ()-->() MATCH ({n1:0})--() RETURN 0 AS n2
```

I encountered the following error:
```
column reference "_age_default_alias_0" is ambiguous
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **apache/age:PG13_latest** docker image.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
MATCH ({n0:0}) MATCH ()-->() MATCH ({n1:0})--() RETURN 0 AS n2
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `column reference "_age_default_alias_0" is ambiguous`.

### PR DESCRIPTION
**Pull request by MuhammadTahaNaveed**
- The problem was with get_next_default_alias function which was not generating unique aliases.
- Every clause transformed as a subquery has its own cpstate which is being freed after it is tranformed. The root cpstate is the one that has the default_alias_number initialized. So we need to reach the root cpstate to get the next correct default alias number.
- This change also fixed some previously incorrect results (verified using neo4j).
- Added additional regression tests.

Resolves #876

### CODE REVIEW

File: src/backend/parser/cypher_parse_node.c [hunk 1]
```diff
@@ -131,9 +131,20 @@ RangeTblEntry *find_rte(cypher_parsestate *cpstate, char *varname)
...
     char *alias_name;
     int nlen = 0;
 
+    /*
+     * Every clause transformed as a subquery has its own cpstate which is being
+     * freed after it is tranformed. The root cpstate is the one that has the
+     * default alias number initialized. So we need to reach the root cpstate to
+     * get the next correct default alias number.
+     */
+    if (parent_cpstate)
```
Comment (jrgemignani) [inline src/backend/parser/cypher_parse_node.c:145]: Remember to add {} for all if/else

**Review by jrgemignani — CHANGES_REQUESTED** [review]
Minor coding issue.

File: src/backend/parser/cypher_parse_node.c (hunk 1 above)
Comment (MuhammadTahaNaveed) [reply src/backend/parser/cypher_parse_node.c:145]: Fixed it
