### PR TITLE
Fix issue #878 - unrecognized node type error

### LINKED ISSUE #878: Unexpected Error: unrecognized node type: 107
When running the following query:
```cypher
MERGE ({n0:(null IS NULL)})
```

I encountered the following error:
```
unrecognized node type: 107
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **apache/age:PG13_latest** docker image.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
MERGE ({n0:(null IS NULL)})
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `unrecognized node type: 107`.

### PR DESCRIPTION
**Pull request by MuhammadTahaNaveed**
- The error was in the way expr was getting transformed in case of T_NullTest.
- The original expr was also getting tranformed, causing the nodeType of that expr unrecognizable next time the expr is used.
- Fixed by creating a new NullTest expr.
- Added regression tests as well.

resolves #878

### CODE REVIEW

File: src/backend/parser/cypher_expr.c [hunk 1]
```diff
@@ -152,12 +152,15 @@ static Node *transform_cypher_expr_recurse(cypher_parsestate *cpstate,
     case T_NullTest:
     {
         NullTest *n = (NullTest *)expr;
+        NullTest *tranformed_expr = makeNode(NullTest);
```
Comment (jrgemignani) [inline src/backend/parser/cypher_expr.c:155]: Is there a particular reason for creating a new node as opposed to using the passed node?

**Comment by jrgemignani** [comment]
@MuhammadTahaNaveed Added a question, otherwise it looks good.

File: src/backend/parser/cypher_expr.c (hunk 1 above)
Comment (jrgemignani) [reply src/backend/parser/cypher_expr.c:155]: Actually, what about using the transformed node and just checking to see if it was already transformed?

**Comment by MuhammadTahaNaveed** [comment]
@jrgemignani where? I could not see it.

**Comment by jrgemignani** [comment]
@MuhammadTahaNaveed 
image

**Review by jrgemignani — APPROVED** [review]
